name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kimiakarbin
          template: classic
          base: header, repositories
          config_timezone: Europe/Rome
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
